version: "3"
services:
  app:
    build: 
      context: ./src
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8080:8080"
    volumes:
      - ./src/static:/app/static
      - ./src/templates:/app/templates
      - ./src/temp.db:/app/temp.db
    environment:
      - PYTHONUNBUFFERED=1
  bot:
    build: 
      context: ./poster
      dockerfile: Dockerfile
    container_name: bot
    restart: unless-stopped
    environment:
      - OPENWEATHER_API_KEY=2bc993ef-b477-4921-a92c-6f4befc22ffe
      - API_KEY=ebe9323dd4d66a4bb1b75ea1fc85302c
    network_mode: "host"
    depends_on:
      - app
    ports:
      - "3000:3000"
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 3


